### ISSUE TITLE
TODO before production

### ISSUE THREAD

**Issue by nicogarcia** [tomasgil123/lead-landing-upclaz#1]
### Required
- [ ] Add `target="_blank"` to all external links
- [ ] Import external css in index.js and remove from <script>
- [ ] Import external js in index.js and remove from <script>
- [ ] Check spell in all files
- [ ] Serve images from the project, not from cloudinary (to enable webpack to inline them if necessary)

### Nice to have
- [ ] Import component's css from component js
- [ ] Remove words 'presentational' and 'container' from folders
- [ ] Use export default from index.js inside a folder with the component name to tide up components

**Comment by federicojasson** [comment]
Move project to github.com/upclaz
